// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZYxNOKpU6NiaMbui4503E6nyY2cWpHDw',
    appId: '1:41505777236:web:697f7d4ae94713bde16fc1',
    messagingSenderId: '41505777236',
    projectId: 'shopping-app-37644',
    authDomain: 'shopping-app-37644.firebaseapp.com',
    databaseURL: 'https://shopping-app-37644-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shopping-app-37644.appspot.com',
    measurementId: 'G-JB06VTQ3BN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuv9DZkVkn6xdBCK9hila3cfFpT3ykU4U',
    appId: '1:41505777236:android:1a0f2b61f7a23130e16fc1',
    messagingSenderId: '41505777236',
    projectId: 'shopping-app-37644',
    databaseURL: 'https://shopping-app-37644-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shopping-app-37644.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfXucgaspNhIC0ChuBcLScIMh1skQ9ILc',
    appId: '1:41505777236:ios:8be486032249738de16fc1',
    messagingSenderId: '41505777236',
    projectId: 'shopping-app-37644',
    databaseURL: 'https://shopping-app-37644-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shopping-app-37644.appspot.com',
    iosBundleId: 'com.example.techVeritoAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfXucgaspNhIC0ChuBcLScIMh1skQ9ILc',
    appId: '1:41505777236:ios:ca384f3f24e3dadee16fc1',
    messagingSenderId: '41505777236',
    projectId: 'shopping-app-37644',
    databaseURL: 'https://shopping-app-37644-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shopping-app-37644.appspot.com',
    iosBundleId: 'com.example.techVeritoAssignment.RunnerTests',
  );
}
